### ISSUE TITLE
FS17 upgrade?

### ISSUE THREAD

**Issue by DeckerMMIV** [DeckerMMIV/FarmSim_Mod_VehicleGroupsSwitcher#4]
Your question: Is this going to be upgraded to FS17?

My answer: Yes it is. - Hopefully available via the in-game mod browser.

**Comment by Gonimy-Vetrom** [comment]
Hooray. I look forward to.

**Comment by mereman** [comment]
Good I now realise how many of your mods I use on FS15 and miss on FS17

**Comment by Dzi4d3k** [comment]
Can't wait to see it... Keeping fingers crossed :D

**Comment by TheRealestMcCoy** [comment]
Do you have any ETA when this will be ready for 17? Or is it a full rewrite?

**Comment by DeckerMMIV** [comment]
The first version I uploaded to ModHub, they discovered a critical flaw so was rejected.

I spend some time to fix it, and the second version, which I uploaded to ModHub two days ago, is still in "being tested"-state - so we're actually waiting on GIANTS Software's mod-testing team, which I'm guessing have lots of work to do.

I will not publish it here yet, due to their ModHub rules: `If a Mod is published on
another download portal prior to completion of testing, the testing is discontinued and the Mod is rejected.`

**Comment by TheRealestMcCoy** [comment]
@DeckerMMIV  Can you be so kind as to let us know when they are available to download from the site?

**Comment by DeckerMMIV** [comment]
@TheRealestMcCoy - Is has been released on ModHub
http://www.farming-simulator.com/mod.php?mod_id=54509&title=fs2017
